#!/usr/bin/env node
// -----------------------------------------------------------------------------
// sync-content.mjs
//
// Turns knowledge-base write-ups into Astro blog posts, deterministically.
//
//   node scripts/sync-content.mjs           # write posts + prune stale ones
//   node scripts/sync-content.mjs --check   # dry run; exit 1 on any error
//
// For each entry in ../content.sources.mjs it:
//   - applies literal `replace` rules and strips <!-- blog:skip --> spans
//   - drops the leading H1 (the layout renders the title)
//   - rewrites cross-post links (other write-ups -> /blog/<slug>, keeping
//     #anchors, swapping filename labels for the post title)
//   - copies hero + inline images into /public and rewrites their paths
//   - unlinks any remaining local link (keeps the text) so nothing ships broken
//   - writes frontmatter + a @generated marker, then prunes generated posts
//     whose slug is no longer in the manifest
// -----------------------------------------------------------------------------
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { KB_PATH, posts } from '../content.sources.mjs';

const ROOT = path.resolve(fileURLToPath(new URL('..', import.meta.url)));
const BLOG_DIR = path.join(ROOT, 'src/content/blog');
const PUBLIC_DIR = path.join(ROOT, 'public');
const GEN_MARK = '@generated by scripts/sync-content.mjs';
const CHECK = process.argv.includes('--check');

const errors = [];
const warnings = [];
const written = [];

const rel = (p) => path.relative(ROOT, p);
const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const isFilenameLabel = (label) =>
  /^`?\.{0,2}\/?[\w./-]+\.md`?$/.test(label.trim());

// map every source basename -> { slug, title } for cross-link rewriting
const bySource = new Map();
for (const p of posts) bySource.set(path.basename(p.source), { slug: p.slug, title: p.title });

function applyReplaces(text, rules, id) {
  for (const [from, to] of rules ?? []) {
    if (!text.includes(from)) {
      errors.push(`[${id}] replace rule did not match (source changed?): ${JSON.stringify(from.slice(0, 60))}...`);
      continue;
    }
    text = text.split(from).join(to);
  }
  return text;
}

const stripSkip = (t) =>
  t.replace(/<!--\s*blog:skip\s*-->[\s\S]*?<!--\s*\/blog:skip\s*-->\n?/g, '');

const stripH1 = (t) => t.replace(/^﻿?#\s+.*\r?\n/, '').replace(/^\s+/, '');

function rewriteCrossLinks(text, id) {
  for (const [basename, { slug, title }] of bySource) {
    const re = new RegExp(
      // [label](optional/prefix/basename.md#optional-anchor)
      `\\[([^\\]]+)\\]\\(([^)]*?/)?${esc(basename)}(#[^)]*)?\\)`,
      'g',
    );
    text = text.replace(re, (_m, label, _pre, anchor = '') => {
      const newLabel = isFilenameLabel(label) ? title : label;
      return `[${newLabel}](/blog/${slug}${anchor})`;
    });
  }
  return text;
}

function copyImages(text, srcDir, slug) {
  return text.replace(/!\[([^\]]*)\]\(([^)\s]+)([^)]*)\)/g, (m, alt, src, tail) => {
    if (/^(https?:|data:|\/)/.test(src)) return m; // external or already-public
    const abs = path.resolve(srcDir, src);
    if (!fs.existsSync(abs)) {
      warnings.push(`[${slug}] inline image not found, left as-is: ${src}`);
      return m;
    }
    const destRel = `imported/${slug}/${path.basename(abs)}`;
    if (!CHECK) {
      fs.mkdirSync(path.join(PUBLIC_DIR, 'imported', slug), { recursive: true });
      fs.copyFileSync(abs, path.join(PUBLIC_DIR, destRel));
    }
    return `![${alt}](/${destRel}${tail})`;
  });
}

function unlinkLocal(text, id) {
  // any [text](href) that isn't external, mailto/tel, in-page (#) or site-absolute (/)
  const re = /(?<!\!)\[([^\]]+)\]\(\s*((?!https?:|mailto:|tel:|#|\/)[^)\s]+)\s*\)/g;
  return text.replace(re, (_m, label, href) => {
    warnings.push(`[${id}] unlinked local reference (kept text): ${href}`);
    return label;
  });
}

function frontmatter(p) {
  const lines = ['---'];
  lines.push(`title: ${JSON.stringify(p.title)}`);
  lines.push(`description: ${JSON.stringify(p.description)}`);
  lines.push(`pubDate: ${p.pubDate}`);
  if (p.updatedDate) lines.push(`updatedDate: ${p.updatedDate}`);
  lines.push(`tags: [${p.tags.map((t) => JSON.stringify(t)).join(', ')}]`);
  lines.push(`featured: ${p.featured ? 'true' : 'false'}`);
  if (p.hero) lines.push(`heroImage: ${JSON.stringify('/' + path.basename(p.hero))}`);
  lines.push('---');
  return lines.join('\n');
}

// --- build each post -------------------------------------------------------
if (!fs.existsSync(KB_PATH)) {
  console.error(`\n✗ KB_PATH does not exist: ${KB_PATH}\n  Set the KB_PATH env var to your knowledge-base checkout.\n`);
  process.exit(1);
}
if (!CHECK) fs.mkdirSync(BLOG_DIR, { recursive: true });

for (const p of posts) {
  const srcAbs = path.join(KB_PATH, p.source);
  if (!fs.existsSync(srcAbs)) {
    errors.push(`[${p.slug}] source not found: ${p.source}`);
    continue;
  }
  let body = fs.readFileSync(srcAbs, 'utf8');
  body = applyReplaces(body, p.replace, p.slug);
  body = stripSkip(body);
  body = stripH1(body);
  body = copyImages(body, path.dirname(srcAbs), p.slug);
  body = rewriteCrossLinks(body, p.slug);
  body = unlinkLocal(body, p.slug);

  if (p.hero) {
    const heroAbs = path.join(KB_PATH, p.hero);
    if (!fs.existsSync(heroAbs)) {
      errors.push(`[${p.slug}] hero not found: ${p.hero}`);
    } else if (!CHECK) {
      fs.copyFileSync(heroAbs, path.join(PUBLIC_DIR, path.basename(p.hero)));
    }
  }

  const marker = `<!-- ${GEN_MARK} from ${p.source} — edit the source, not this file -->`;
  const out = `${frontmatter(p)}\n${marker}\n\n${body.replace(/\s*$/, '')}\n`;
  const dest = path.join(BLOG_DIR, `${p.slug}.md`);
  if (!CHECK) fs.writeFileSync(dest, out);
  written.push({ slug: p.slug, source: p.source, bytes: out.length });
}

// --- prune generated posts no longer in the manifest -----------------------
const keep = new Set(posts.map((p) => `${p.slug}.md`));
if (fs.existsSync(BLOG_DIR)) {
  for (const f of fs.readdirSync(BLOG_DIR)) {
    if (!f.endsWith('.md') || keep.has(f)) continue;
    const contents = fs.readFileSync(path.join(BLOG_DIR, f), 'utf8');
    if (contents.includes(GEN_MARK)) {
      warnings.push(`pruned stale generated post: ${f}`);
      if (!CHECK) fs.rmSync(path.join(BLOG_DIR, f));
    }
  }
}

// --- report ----------------------------------------------------------------
console.log(`\n${CHECK ? 'sync --check' : 'sync'}  (KB: ${KB_PATH})\n`);
for (const w of written) console.log(`  ✓ ${w.slug.padEnd(24)} ← ${w.source}`);
if (warnings.length) {
  console.log('\n  warnings:');
  for (const w of warnings) console.log(`    - ${w}`);
}
if (errors.length) {
  console.log('\n  errors:');
  for (const e of errors) console.log(`    ✗ ${e}`);
}
console.log(
  `\n${errors.length ? '✗' : '✓'} ${written.length} post(s), ${warnings.length} warning(s), ${errors.length} error(s)\n`,
);
process.exit(errors.length ? 1 : 0);
